name: docdeploy
on:
  push:
    branches:
      - main
    paths:
      - 'docsite/**'
jobs:
  deploy-docsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docusaurus website
        run: |
          cd docsite
          yarn install 
          yarn run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docsite/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}